package strategy

import (
	"context"
	"time"
	"github.com/isxcli/isxcli/internal/liquidity"
)

// Strategy defines the interface that all trading strategies must implement
type Strategy interface {
	ID() string
	Name() string
	Description() string
	Parameters() StrategyParams
	Execute(ctx context.Context, data []liquidity.TradingDay) (Signal, error)
	Validate(ctx context.Context, params StrategyParams) error
	Backtest(ctx context.Context, data []liquidity.TradingDay, config BacktestConfig) (BacktestResult, error)
}

// StrategyParams holds configuration parameters for strategies
type StrategyParams map[string]interface{}

// Signal represents a trading signal generated by a strategy
type Signal struct {
	ID           string                 `json:"id"`
	StrategyID   string                 `json:"strategy_id"`
	Symbol       string                 `json:"symbol"`
	Action       SignalAction           `json:"action"`
	Strength     float64                `json:"strength"`     // 0-100 confidence
	Price        float64                `json:"price"`
	Quantity     int64                  `json:"quantity"`
	Timestamp    time.Time              `json:"timestamp"`
	Reasoning    string                 `json:"reasoning"`
	Metadata     map[string]interface{} `json:"metadata"`
	ValidUntil   time.Time              `json:"valid_until"`
}

type SignalAction string

const (
	SignalBuy  SignalAction = "BUY"
	SignalSell SignalAction = "SELL"
	SignalHold SignalAction = "HOLD"
)

// BacktestConfig defines parameters for backtesting
type BacktestConfig struct {
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	InitialCash float64   `json:"initial_cash"`
	Commission  float64   `json:"commission"`
	Slippage    float64   `json:"slippage"`
}

// BacktestResult contains the results of a strategy backtest
type BacktestResult struct {
	StrategyID       string    `json:"strategy_id"`
	Symbol           string    `json:"symbol"`
	StartDate        time.Time `json:"start_date"`
	EndDate          time.Time `json:"end_date"`
	TotalReturn      float64   `json:"total_return"`
	AnnualizedReturn float64   `json:"annualized_return"`
	Volatility       float64   `json:"volatility"`
	SharpeRatio      float64   `json:"sharpe_ratio"`
	MaxDrawdown      float64   `json:"max_drawdown"`
	WinRate          float64   `json:"win_rate"`
	TotalTrades      int       `json:"total_trades"`
	Signals          []Signal  `json:"signals"`
}

// StrategyType enum for different strategy categories
type StrategyType string

const (
	StrategyTypeMomentum      StrategyType = "MOMENTUM"
	StrategyTypeMeanReversion StrategyType = "MEAN_REVERSION"
	StrategyTypeLiquidity     StrategyType = "LIQUIDITY_BASED"
	StrategyTypeVolume        StrategyType = "VOLUME_WEIGHTED"
	StrategyTypeCustom        StrategyType = "CUSTOM"
)

// StrategyInfo contains metadata about a strategy
type StrategyInfo struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Type        StrategyType `json:"type"`
	Version     string       `json:"version"`
	Author      string       `json:"author"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Parameters  []ParamInfo  `json:"parameters"`
}

// ParamInfo describes a strategy parameter
type ParamInfo struct {
	Name         string      `json:"name"`
	Type         string      `json:"type"`
	DefaultValue interface{} `json:"default_value"`
	Description  string      `json:"description"`
	Required     bool        `json:"required"`
	Min          *float64    `json:"min,omitempty"`
	Max          *float64    `json:"max,omitempty"`
}