import type { DrawingStyle, DrawingToolDefinition } from './types'

export const DEFAULT_DRAWING_STYLE: DrawingStyle = {
  strokeColor: '#2563eb',
  strokeWidth: 2,
  strokeStyle: 'solid',
  fillColor: 'rgba(37, 99, 235, 0.12)',
  textColor: '#111827',
  opacity: 1,
}

export const PHASE_ONE_TOOLS: DrawingToolDefinition[] = [
  {
    id: 'select',
    label: 'Select',
    cursor: 'default',
  },
  {
    id: 'trend-line',
    label: 'Trend Line',
    cursor: 'crosshair',
    shapeType: 'trendLine',
    requiredPoints: 2,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'trendLine',
    hitTest: 'trendLine',
  },
  {
    id: 'ray',
    label: 'Ray',
    cursor: 'crosshair',
    shapeType: 'ray',
    requiredPoints: 2,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'ray',
    hitTest: 'ray',
  },
  {
    id: 'parallel-channel',
    label: 'Parallel Channel',
    cursor: 'crosshair',
    shapeType: 'parallelChannel',
    requiredPoints: 3,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'parallelChannel',
    hitTest: 'parallelChannel',
  },
  {
    id: 'horizontal-line',
    label: 'Horizontal Line',
    cursor: 'crosshair',
    shapeType: 'horizontalLine',
    requiredPoints: 1,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'horizontalLine',
    hitTest: 'horizontalLine',
  },
  {
    id: 'vertical-line',
    label: 'Vertical Line',
    cursor: 'crosshair',
    shapeType: 'verticalLine',
    requiredPoints: 1,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'verticalLine',
    hitTest: 'verticalLine',
  },
  {
    id: 'rectangle',
    label: 'Rectangle',
    cursor: 'crosshair',
    shapeType: 'rectangle',
    requiredPoints: 2,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'rectangle',
    hitTest: 'rectangle',
  },
  {
    id: 'text',
    label: 'Text',
    cursor: 'text',
    shapeType: 'text',
    requiredPoints: 1,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'text',
    hitTest: 'text',
  },
  {
    id: 'arrow',
    label: 'Arrow',
    cursor: 'crosshair',
    shapeType: 'arrow',
    requiredPoints: 2,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'arrow',
    hitTest: 'arrow',
  },
  {
    id: 'measure',
    label: 'Measure',
    cursor: 'crosshair',
    shapeType: 'measure',
    requiredPoints: 2,
    defaultStyle: DEFAULT_DRAWING_STYLE,
    renderer: 'measure',
    hitTest: 'measure',
  },
]

export const ALL_DRAWING_TOOLS: DrawingToolDefinition[] = [...PHASE_ONE_TOOLS]
